### ISSUE TITLE
RiemannTheta Intermittent Error

### ISSUE THREAD

**Issue by RParini** [cswiercz/abelfunctions#84]
The RiemannTheta function will, intermittently, give an incorrect result for certain Riemann matrices.  For example, the following:
```python
from abelfunctions import RiemannTheta

z = [0.5-1.10093687j, -0.11723434j]
omega = [[0.5+2j, 0.5+1j], [0.5+1j, 1+1.5j]]

for i in xrange(100):
	print RiemannTheta(z, omega)
```
gives me
```
(0.963179246467-6.2286820685j)
(0.963179246467-6.2286820685j)
(0.963179246467-6.22868021896j)
(0.963179246467-6.2286820685j)
(0.963179246467-6.2286820685j)
(0.963179246467-6.2286820685j)
(0.963179246467-6.2286820685j)
(0.963179246467-6.2286820685j)
(0.963179246467-6.2286820685j)
(0.963179246467-6.2286820685j)
0j
(0.963179246467-6.2286820685j)
(0.963179246467-6.22868021896j)
(-3.36185462314-18.9728228077j)
(0.963179246467-6.2286820685j)
(0.963179246467-6.2286820685j)
(0.963179246467-6.2286820685j)
(0.963179246467-6.2286820685j)
(0.963179246467-6.2286820685j)
(0.963179246467-6.2286820685j)
(0.963179246467-6.2286820685j)
(0.963179246467-6.22868021896j)
(0.963179246467-6.22868021896j)
(0.963179246467-6.2286820685j)
(0.963179246467-6.22868021896j)
0j
(0.963179246467-6.2286820685j)
(0.963179246467-6.2286820685j)
(0.963179246467-6.2286820685j)
```
ect... Returning 0 seems to be the most common error but there's also others like the (-3.36185462314-18.9728228077j) above. According to Mathematica the actual answer is 0.963179 - 6.22868 i so it's correct most of the time.  Running the above also occasionally gives me the following error (though not always):
```
RiemannThetaBug.py:7: RuntimeWarning: divide by zero encountered in double_scalars
  print RiemannTheta(z, omega)
Traceback (most recent call last):
  File "RiemannThetaBug.py", line 7, in <module>
    print RiemannTheta(z, omega)
  File "abelfunctions/riemann_theta/riemann_theta.pyx", line 155, in abelfunctions.riemann_theta.riemann_theta.RiemannTheta_Function.__call__ (abelfunctions/riemann_theta/riemann_theta.c:3129)
  File "abelfunctions/riemann_theta/riemann_theta.pyx", line 182, in abelfunctions.riemann_theta.riemann_theta.RiemannTheta_Function.eval (abelfunctions/riemann_theta/riemann_theta.c:3296)
  File "abelfunctions/riemann_theta/riemann_theta.pyx", line 268, in abelfunctions.riemann_theta.riemann_theta.RiemannTheta_Function.oscillatory_part (abelfunctions/riemann_theta/riemann_theta.c:4139)
  File "abelfunctions/riemann_theta/riemann_theta.pyx", line 90, in abelfunctions.riemann_theta.riemann_theta.oscillatory_part (abelfunctions/riemann_theta/riemann_theta.c:2230)
  File "abelfunctions/riemann_theta/integer_points.pyx", line 370, in abelfunctions.riemann_theta.integer_points.integer_points_python (abelfunctions/riemann_theta/integer_points.c:4810)
  File "abelfunctions/riemann_theta/integer_points.pyx", line 335, in abelfunctions.riemann_theta.integer_points._find_int_points_python (abelfunctions/riemann_theta/integer_points.c:4180)
OverflowError: cannot convert float infinity to integer
```
As well as the 'positive definite error' (though again it's intermittent):
```
Traceback (most recent call last):
  File "RiemannThetaBug.py", line 18, in <module>
    print RiemannTheta(z, omega)
  File "abelfunctions/riemann_theta/riemann_theta.pyx", line 155, in abelfunctions.riemann_theta.riemann_theta.RiemannTheta_Function.__call__ (abelfunctions/riemann_theta/riemann_theta.c:3129)
  File "abelfunctions/riemann_theta/riemann_theta.pyx", line 182, in abelfunctions.riemann_theta.riemann_theta.RiemannTheta_Function.eval (abelfunctions/riemann_theta/riemann_theta.c:3296)
  File "abelfunctions/riemann_theta/riemann_theta.pyx", line 268, in abelfunctions.riemann_theta.riemann_theta.RiemannTheta_Function.oscillatory_part (abelfunctions/riemann_theta/riemann_theta.c:4139)
  File "abelfunctions/riemann_theta/riemann_theta.pyx", line 82, in abelfunctions.riemann_theta.riemann_theta.oscillatory_part (abelfunctions/riemann_theta/riemann_theta.c:1970)
  File "/usr/local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 603, in cholesky
    return wrap(gufunc(a, signature=signature, extobj=extobj).astype(result_t))
  File "/usr/local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 93, in _raise_linalgerror_nonposdef
    raise LinAlgError("Matrix is not positive definite")
numpy.linalg.linalg.LinAlgError: Matrix is not positive definite
```

It's worth noting this doesn't seem to happen for all Riemann matrices.  For example running the above with 
```python
omega = [[0.5+2j, 0.5+1j], [0.5+1j, 1+1.6j]]
```
seems to give the right answer (or at least I haven't yet seen it give the wrong answer).  I don't yet have a general condition on the Riemann matrix for when this intermittent problem happens .  
The 'Matrix is not positive definite' error above, despite the fact that the imaginary part certainly is positive definite, makes me think that perhaps the Riemann matrix is being inadvertently altered at some point?  Though at a glance your method seems completely deterministic so I can't imagine why this is only happening some of the time.  If it makes any difference I'm on OSX 10.10.2 with Python 2.7.9.

p.s. Notwithstanding the above I can see this module being a very useful resource, thanks for working on it!

**Comment by cswiercz** [comment]
@RParini Thank you very much for reporting this issue. Also, thank you for reporting your operating system and Python version. I was able to replicate your issue.

This is indicative of some sort of memory allocation-related issue. I'll take a look and post here when a solution is available.

**Comment by cswiercz** [comment]
The following is mostly for my own issue tracking purposes but here's where the issue comes from: `abelfunctions.riemann_theta.radius.radius` is an intermediate calculation for determining the set of integer points over which to approximate the infinite sum defining Riemann theta. Here's some erroneous output:

```python
import numpy
import abelfunctions.riemann_theta.radius as radius
from abelfunctions import RiemannTheta

z = [0.5-1.10093687j, -0.11723434j]
omega = numpy.array([[0.5+2j, 0.5+1j], [0.5+1j, 1+1.5j]], dtype=numpy.complex)
Y = omega.imag
T = numpy.linalg.cholesky(Y).T

for i in xrange(100):
    #print RiemannTheta(z, omega)
    print radius.radius(1e-8,T)
```
```
5.01708695504
5.01708695504
5.01708695504
5.01708695504
5.01708695504
5.01708695504
5.01708695504
5.01708695504
4.90475696578
nan
5.01708695504
5.01708695504
5.01708695504
5.01708695504
5.01708695504
... (etc)
```

**Comment by cswiercz** [comment]
@RParini The issue should be fixed now. Pull the latest changes and try again. And please let me know if you experience any more issues.

Thank you again for pointing this out!

**Comment by RParini** [comment]
Yep, seems to be working well now, thanks very much!
